In [13]:
import pandas as pd
import numpy as np
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
#read in the data
data = pd.read_csv("solr_us_10k.csv") 

In [3]:
#get a hint of how data looks
col_names = data.columns.values 
print col_names
#print data.describe()
data.head()

['dur' 'indications' 'lot_num' 'age_cod' 'occp_cod' 'reporter_country'
 'auth_num' 'role_cod' 'to_mfr' 'outcomes' 'rept_dt' 'prod_ai' 'i_f_cod'
 'age_grp' 'image' 'nda_num' 'dose_form' 'drugname' 'cum_dose_chr'
 'primaryid' 'dechal' 'route' 'dur_cod' 'wt_cod' 'lit_ref' 'caseid'
 'drug_seq' 'mfr_sndr' 'mfr_dt' 'rechal' 'event_dt' 'mfr_num' 'lot_nbr'
 'dose_freq' 'e_sub' 'company' 'exp_dt' 'foll_seq' 'dose_vbm' 'wt'
 'death_dt' 'end_dt' 'dose_amt' 'occr_country' 'caseversion' 'val_vbm'
 'sex' 'dsg_drug_seq' 'gndr_cod' 'cum_dose_unit' 'dose_unit' 'rept_cod'
 'reactions' 'age' 'quarter' 'i_f_code']


dur                          indications    lot_num age_cod occp_cod  \
0  NaN                         OSTEOPOROSIS   A719441C      YR       CN   
1  NaN                         OSTEOPOROSIS   A713108C      YR       CN   
2  NaN                         OSTEOPOROSIS        NaN      YR       CN   
3  NaN                         OSTEOPOROSIS   A713108C     NaN       CN   
4  NaN  PRODUCT USED FOR UNKNOWN INDICATION        NaN     NaN       CN   

  reporter_country auth_num role_cod  to_mfr outcomes   ...     sex  \
0               US      NaN       PS     NaN      NaN   ...       F   
1               US      NaN       PS     NaN      NaN   ...       F   
2               US      NaN       PS     NaN      NaN   ...       F   
3               US      NaN       PS     NaN      NaN   ...       F   
4               US      NaN       PS     NaN      NaN   ...       F   

  dsg_drug_seq  gndr_cod cum_dose_unit  dose_unit  rept_cod  \
0            1       NaN           NaN         UG       PER   
1            1       NaN           NaN         UG       PER   
2            1       NaN           NaN         UG       PER   
3            1       NaN           NaN         UG       PER   
4            1       NaN           NaN         MG       PER   

                                           reactions     age  quarter i_f_code  
0  INJECTION SITE BRUISING\,DYSPEPSIA\,ARTHRALGIA...  66.196     15Q4        I  
1             MUSCLE SPASMS\,PAIN\,PAIN IN EXTREMITY  71.734     15Q4        I  
2  LOCAL SWELLING\,PRURITUS\,CONCUSSION\,MYALGIA\...  71.869     15Q4        I  
3                                INJECTION SITE RASH     NaN     15Q4        I  
4                                                TIC     NaN     15Q4        I  

[5 rows x 56 columns]

In [4]:
#get the column that needs to be encoded
gender = data['sex']
reactions = data['reactions']
indications = data['indications']

In [5]:
def hot_pot_encoding(values):
    # integer encode
    label_encoder = LabelEncoder()
    integer_encoded = label_encoder.fit_transform(values)
    print(integer_encoded)
    # binary encode
    onehot_encoder = OneHotEncoder(sparse=False)
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    print(onehot_encoded)
    return label_encoder,onehot_encoded

def reverse_encoding(label_encoder,onehot_encoded):
    # invert first example
    #inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
    inverted = label_encoder.inverse_transform([argmax(onehot_encoded)])
    print(inverted)
    return inverted

In [6]:
#gender hotpot encoding
gender_values = array(gender)
print(gender_values)
gender_label_encoder,gender_onehot_encoded = hot_pot_encoding(gender_values)
#gender_inverted = reverse_encoding(gender_label_encoder,gender_onehot_encoded)

#reaction hotpot encoding
reactions_values = array(reactions)
print(reactions_values)
reactions_label_encoder,reactions_onehot_encoded = hot_pot_encoding(reactions_values)
#reactions_inverted = reverse_encoding(reactions_label_encoder,reactions_onehot_encoded)

#reaction hotpot encoding
indications_values = array(indications)
print(indications_values)
indications_label_encoder,indications_onehot_encoded = hot_pot_encoding(indications_values)
#indications_inverted = reverse_encoding(indications_label_encoder,indications_onehot_encoded)

['F' 'F' 'F' ..., 'F' 'F' 'F']
[1 1 1 ..., 1 1 1]
[[ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 ..., 
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
[ 'INJECTION SITE BRUISING\\,DYSPEPSIA\\,ARTHRALGIA\\,INJECTION SITE ERYTHEMA\\,SKIN IRRITATION\\,INJECTION SITE PRURITUS\\,PAIN\\,HEADACHE'
 'MUSCLE SPASMS\\,PAIN\\,PAIN IN EXTREMITY'
 'LOCAL SWELLING\\,PRURITUS\\,CONCUSSION\\,MYALGIA\\,FALL\\,PAIN\\,INJECTION SITE ERYTHEMA\\,CONTUSION'
 ...,
 'CEREBROVASCULAR ACCIDENT\\,NECK PAIN\\,ANXIETY\\,HEMIPARESIS\\,MIGRAINE\\,ARTHRALGIA\\,BACK PAIN\\,MENTAL DISORDER\\,COGNITIVE DISORDER\\,DEPRESSION\\,HEADACHE'
 'CEREBROVASCULAR ACCIDENT\\,EMBOLISM ARTERIAL'
 'GASTROOESOPHAGEAL REFLUX DISEASE\\,WEIGHT DECREASED\\,CARDIAC VALVE DISEASE\\,BLOOD GLUCOSE INCREASED\\,HYPOACUSIS\\,FEELING ABNORMAL\\,NASOPHARYNGITIS\\,EAR INFECTION\\,CHEST PAIN\\,DIABETES MELLITUS\\,DIZZINESS\\,DRUG DOSE OMISSION']
[2373 3186 2873 ...,  881  867 1830]
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  

/Users/Smiling/anaconda/lib/python2.7/site-packages/numpy/lib/arraysetops.py:216: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  flag = np.concatenate(([True], aux[1:] != aux[:-1]))


In [10]:
def split_coma(s):
    return s.split('\\,')
reactions_splited = map(split_coma, reactions)
reactions_splited[:2]

[['INJECTION SITE BRUISING',
  'DYSPEPSIA',
  'ARTHRALGIA',
  'INJECTION SITE ERYTHEMA',
  'SKIN IRRITATION',
  'INJECTION SITE PRURITUS',
  'PAIN',
  'HEADACHE'],
 ['MUSCLE SPASMS', 'PAIN', 'PAIN IN EXTREMITY']]

In [28]:
reaction_flat_list = [item for sublist in reactions_splited for item in sublist]
#reactions_flat = np.asarray(reactions_splited).flatten('F')
#print reaction_flat_list
reaction_set = set(reaction_flat_list)
distinct_reaction = list(reaction_set)

In [29]:
print len(distinct_reaction)

2340


In [33]:
def one_hot_encoding(data, distinct_val):
    encoding_list = []
    for line in data:
        line_list = [0 for i in xrange(len(distinct_val))]
        for item in line:
            idx = distinct_val.index(item)
            line_list[idx] = 1
        encoding_list.append(line_list)
    return encoding_list

In [31]:
def get_distinct_value(splited_list):
    flat_list = [item for sublist in splited_list for item in sublist]
    flat_set = set(flat_list)
    return list(flat_set)

In [37]:
test_reaction_split = reactions_splited[:10]
test_distinct_reactions = get_distinct_value(test_reaction_split)
print test_distinct_reactions
test_encoding_list = one_hot_encoding(test_reaction_split, test_distinct_reactions)
test_encoding_list

['INJECTION SITE BRUISING', 'DYSPEPSIA', 'INJECTION SITE ERYTHEMA', 'SKIN IRRITATION', 'MYALGIA', 'FALL', 'PAIN', 'NAUSEA', 'ARTHRALGIA', 'CONCUSSION', 'BLOOD ALKALINE PHOSPHATASE INCREASED', 'PAIN IN JAW', 'FATIGUE', 'TIC', 'CONTUSION', 'JOINT SWELLING', 'MUSCLE SPASMS', 'LOCAL SWELLING', 'PRURITUS', 'MALAISE', 'PAIN IN EXTREMITY', 'INJECTION SITE PRURITUS', 'INJECTION SITE RASH', 'HEADACHE']


[[1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [38]:
test_reaction_split

[['INJECTION SITE BRUISING',
  'DYSPEPSIA',
  'ARTHRALGIA',
  'INJECTION SITE ERYTHEMA',
  'SKIN IRRITATION',
  'INJECTION SITE PRURITUS',
  'PAIN',
  'HEADACHE'],
 ['MUSCLE SPASMS', 'PAIN', 'PAIN IN EXTREMITY'],
 ['LOCAL SWELLING',
  'PRURITUS',
  'CONCUSSION',
  'MYALGIA',
  'FALL',
  'PAIN',
  'INJECTION SITE ERYTHEMA',
  'CONTUSION'],
 ['INJECTION SITE RASH'],
 ['TIC'],
 ['FATIGUE'],
 ['JOINT SWELLING'],
 ['JOINT SWELLING'],
 ['MALAISE', 'NAUSEA'],
 ['PAIN IN JAW', 'BLOOD ALKALINE PHOSPHATASE INCREASED']]